<a href="https://colab.research.google.com/github/Jeonyujeong/RottenFruitsModel/blob/master/tflite_convert.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Converting a custom Darknet model to TensorFlow Lite
[참고 사이트](https://medium.com/analytics-vidhya/converting-a-custom-darknet-model-to-tensorflow-lite-ffdd48d58082)

In [ ]:
!python --version

Python 3.6.9


In [ ]:
%tensorflow_version 1.x
import tensorflow
print(tensorflow.__version__)

TensorFlow is already loaded. Please restart the runtime to change versions.
2.2.0


In [ ]:
from google.colab import drive
drive.mount('/content/gdrive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/gdrive


In [ ]:
!wget https://raw.githubusercontent.com/pjreddie/darknet/master/data/coco.names
!wget https://raw.githubusercontent.com/mystic123/tensorflow-yolo-v3/master/convert_weights_pb.py
!wget https://raw.githubusercontent.com/mystic123/tensorflow-yolo-v3/master/convert_weights.py

In [ ]:
!wget https://raw.githubusercontent.com/mystic123/tensorflow-yolo-v3/master/yolo_v3.py
!wget https://raw.githubusercontent.com/mystic123/tensorflow-yolo-v3/master/demo.py
!wget https://raw.githubusercontent.com/mystic123/tensorflow-yolo-v3/master/utils.py

In [ ]:
!wget https://raw.githubusercontent.com/mystic123/tensorflow-yolo-v3/master/yolo_v3_tiny.py

In [ ]:
!python ./convert_weights.py

In [ ]:
!cat yolo_v3.py

In [ ]:
!python convert_weights_pb.py --class_names "/content/gdrive/My Drive/darknet/custom/classes.names"\
 --weights_file "/content/gdrive/My Drive/darknet/backup/custom-train-yolo_last.weights" \
 --data_format "NHWC" --tiny

The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.



W0717 04:14:44.823178 140422240294784 module_wrapper.py:139] From convert_weights_pb.py:42: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.


W0717 04:14:44.825248 140422240294784 module_wrapper.py:139] From convert_weights_pb.py:44: The name tf.variable_scope is deprecated. Please use tf.compat.v1.variable_scope instead.

Instructions for updating:
Please use `layer.__call__` method instead.
W0717 04:14:44.829952 140422240294784 deprecation.py:323] From /tensorflow-1.15.2/python3.6/tensorflow_core/contrib/layers/python/layers/layers.py:1057: Layer.apply (from tensorflow.python.keras.engine.

In [ ]:
!pip install netron

     |████████████████████████████████| 1.4MB 2.7MB/s 


In [ ]:
!tflite_convert --graph_def_file=/content/frozen_darknet_yolov3_model.pb\
 --output_file=yolov3-tiny.tflite\
  --input_format=TENSORFLOW_GRAPHDEF \
  --output_format=TFLITE \
  --input_shape=1,416,416,3 \
  --input_array=inputs\
   --output_array=output_boxes\
    --inference_type=FLOAT --input_data_type=FLOAT

2020-07-22 15:18:00.478653: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2020-07-22 15:18:00.481553: E tensorflow/stream_executor/cuda/cuda_driver.cc:318] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
2020-07-22 15:18:00.481627: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (eddc0055b36c): /proc/driver/nvidia/version does not exist
2020-07-22 15:18:00.509598: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2300000000 Hz
2020-07-22 15:18:00.509902: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x1e74a00 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-07-22 15:18:00.509942: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-07-22 15:18:00.794897: I tensorflow/core/grappler/devices

In [ ]:
!pip install --upgrade tf_nightly

In [ ]:
import tensorflow as tf
interpreter = tf.lite.Interpreter(model_path="/content/RottenFruitsModel/metadata_create/yolov3-tiny.tflite")
interpreter.allocate_tensors()

# Print input shape and type
print(interpreter.get_input_details()[0]['shape'])  # Example: [1 224 224 3]
print(interpreter.get_input_details()[0]['dtype'])  # Example: <class 'numpy.float32'>
# Print output shape and type
print(interpreter.get_output_details()[0]['shape'])  # Example: [1 1000]

[  1 416 416   3]
<class 'numpy.float32'>
[   1 2535    9]


demo.py 실행

In [ ]:
!git clone https://github.com/mystic123/tensorflow-yolo-v3.git

Cloning into 'tensorflow-yolo-v3'...
remote: Enumerating objects: 6, done.
remote: Counting objects: 100% (6/6), done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 219 (delta 1), reused 2 (delta 0), pack-reused 213
Receiving objects: 100% (219/219), 59.90 KiB | 5.99 MiB/s, done.
Resolving deltas: 100% (111/111), done.


In [ ]:
%cd tensorflow-yolo-v3/

/content/tensorflow-yolo-v3


In [ ]:
!wget https://raw.githubusercontent.com/pjreddie/darknet/master/data/coco.names

--2020-07-22 14:48:20--  https://raw.githubusercontent.com/pjreddie/darknet/master/data/coco.names
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.0.133, 151.101.64.133, 151.101.128.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.0.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 625 [text/plain]
Saving to: ‘coco.names’

coco.names          100%[===================>]     625  --.-KB/s    in 0s      

2020-07-22 14:48:21 (31.4 MB/s) - ‘coco.names’ saved [625/625]



In [ ]:
!python ./demo.py --input_img /content/cherry_image.jpg --output_img output_cherry --frozen_model /content/frozen_darknet_yolov3_model.pb

# 새로운 방법


In [ ]:
%tensorflow_version 1.x
import tensorflow
print(tensorflow.__version__)

TensorFlow 1.x selected.
1.15.2


In [ ]:
!git clone https://github.com/RottenFruitsOSS/RottenFruitsModel.git

Cloning into 'RottenFruitsModel'...
remote: Enumerating objects: 13, done.
remote: Counting objects: 100% (13/13), done.
remote: Compressing objects: 100% (9/9), done.
remote: Total 13 (delta 1), reused 13 (delta 1), pack-reused 0
Unpacking objects: 100% (13/13), done.


In [ ]:
%cd RottenFruitsModel/metadata_create/

/content/RottenFruitsModel/metadata_create


In [ ]:
import tensorflow as tf
localpb = '/content/RottenFruitsModel/metadata_create/frozen_darknet_yolov3_model.pb'
tflite_file = 'tflite_vesion_2.lite'
print("{} -> {}".format(localpb, tflite_file))
converter = tf.lite.TFLiteConverter.from_frozen_graph(
localpb,
['inputs'],
['output_boxes']
)
tflite_model = converter.convert()
open(tflite_file,'wb').write(tflite_model)

interpreter = tf.lite.Interpreter(model_content=tflite_model)
interpreter.allocate_tensors()

/content/RottenFruitsModel/metadata_create/frozen_darknet_yolov3_model.pb -> tflite_vesion_2.lite


In [ ]:
import tensorflow as tf
interpreter = tf.lite.Interpreter(model_path="/content/RottenFruitsModel/metadata_create/tflite_vesion_2.lite")
interpreter.allocate_tensors()

# Print input shape and type
print(interpreter.get_input_details()[0]['shape'])  # Example: [1 224 224 3]
print(interpreter.get_input_details()[0]['dtype'])  # Example: <class 'numpy.float32'>
# Print output shape and type
print(interpreter.get_output_details()[0]['shape'])  # Example: [1 1000]

[  1 416 416   3]
<class 'numpy.float32'>
[   1 2535    9]


# TensorFlow version 2

In [ ]:
import tensorflow as tf

In [ ]:
!git clone https://github.com/RottenFruitsOSS/RottenFruitsModel.git

Cloning into 'RottenFruitsModel'...
remote: Enumerating objects: 13, done.
remote: Counting objects: 100% (13/13), done.
remote: Compressing objects: 100% (9/9), done.
remote: Total 13 (delta 1), reused 13 (delta 1), pack-reused 0
Unpacking objects: 100% (13/13), done.


In [ ]:
%cd RottenFruitsModel/metadata_create/

/content/RottenFruitsModel/metadata_create


In [ ]:
model = '/content/RottenFruitsModel/metadata_create/frozen_darknet_yolov3_model.pb'
converter = tf.lite.TFLiteConverter.from_keras_model(model)
tflite_model = converter.convert()
open("converted_model.tflite", "wb").write(tflite_model)

In [ ]:
export_dir = "/content/RottenFruitsModel/metadata_create"
converter = tf.lite.TFLiteConverter.from_saved_model(export_dir)
tflite_model = converter.convert()

INFO:tensorflow:Saver not created because there are no variables in the graph to restore


ValueError: ignored